resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/0.yaml
packages:
- .
extra-deps:
- natural-transformation-0.4
# - ./vendor/replica
# - ./vendor/concur-core
- git: https://github.com/O2O-Wind-International/replica.git
  commit: 685225e5cb5a0199a9def93957e2cf3930de818e
- git: https://github.com/pkamenarsky/concur.git
  commit: dc5347b35c79654d58fa95716f425ee7248504fb
  subdirs:
    - concur-core
flags: {}
extra-package-dbs: []
nix:
  enable: true
  packages:
    - "zlib"
  pure: false
